#:import time time

<HomeScreen>:
    orientation: 'vertical'
    
    Label:
        id: display
        text: '00:00:00'
        font_size: 0.5 * self.height
    
    BoxLayout:
        orientation: 'horizontal'
        
        Button:
            text: 'Start'
            on_press: display.text = "Timer started."
            on_press: self.text = 'Stop' if self.text == 'Start' else 'Start'
            
                